default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prepa_examen_development
test:
  <<: *default
  database: prepa_examen_test
production:
  primary: &primary_production
    <<: *default
    database: prepa_examen_production
    username: <%= ENV["PGUSER"] %>
    password: <%= ENV["PGPASSWORD"] %>
  cache:
    <<: *primary_production
    database: prepa_examen_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: prepa_examen_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: prepa_examen_production_cable
    migrations_paths: db/cable_migrate
